### PR TITLE
Major rewrite

### LINKED ISSUE #18: Modifier syntax is non-standard and confusing
Rolling `2d20+5` usually adds the result to the total, not to each dice; it's very uncommon to write `2d20 +5`. I suggest removing the latter (or ignoring the space) and always adding the value to the total.

If you want to get a step farther, check the dice syntax on sites like roll20 - it'd be awesome if the same syntax was used (even though I have to admit that more fancy things such as "keep n highest" are probably not necessary).

### PR DESCRIPTION
**Pull request by svenssonaxel**
This is a major rewrite to support more complex dice expressions. This adds
* Math operators
* Keep/drop functionality
* Comma-separated expressions
* Labels for (sub)expressions
* More

This should be mostly backwards compatible, however there is at least one incompatibility in that `5d6+2` now has the widely-understood meaning to add 2 to the dice total, not 10.
Fixes #18.

This PR also includes [parnic-sks's work](https://github.com/parnic-sks/mattermost-plugin-dice-roller) on ARM64 etc.

### CODE REVIEW

**Comment by moussetc** [comment]
Hi,

Thank you for your interest in the plugin. I have started the review but as it is a big PR, it's going slowly. Don't hesitate to ping me next weekend if you don't hear from me.

**Comment by svenssonaxel** [comment]
Thank you for your reviewing effort. Don't hesitate to ask when things are unclear; I'm aware that this PR isn't particularly well commented.

So far I'm aware of one bug in this PR: Roll expressions allow division by zero, which

**Comment by svenssonaxel** [comment]
Thank you for your reviewing effort. Don't hesitate to ask when things are unclear; I'm aware that this PR isn't particularly well commented.

So far I'm aware of one bug in this PR: Roll expressions allow division by zero, which will crash the plugin. I'm hoping to fix this, as well as add a few more features, soon. Would you like me to push those to this PR, or would you prefer to have them separately?

**Comment by moussetc** [comment]
Hi again, the scope of this PR is just too big, could you try to submit smaller PRs that focus on separate topics, please?

**Comment by svenssonaxel** [comment]
> Hi again, the scope of this PR is just too big, could you try to submit smaller PRs that focus on separate topics, please?

Fair enough. Might take a good while before I get to it though.

> If you have new features in mind, please discuss them in the Issues sections before implementing.

Most of it is already implemented, but I'll be open to discussion after PRs are made.

**Pull request closed without merging**
